DROP TABLE IF EXISTS USER_ACCOUNT CASCADE;
DROP TABLE IF EXISTS MUSHROOM CASCADE;
DROP TABLE IF EXISTS BLOG CASCADE;
DROP TABLE IF EXISTS FRIENDS CASCADE;
DROP TABLE IF EXISTS FAVOURITES CASCADE;
DROP TABLE IF EXISTS MUSHROOM_POST CASCADE;
DROP TABLE IF EXISTS COMMENTS CASCADE;

CREATE TABLE USER_ACCOUNT (
  ID SERIAL PRIMARY KEY NOT NULL,
  FULLNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  PHOTO_URL VARCHAR(255)
);

CREATE TABLE MUSHROOM (
  ID SERIAL PRIMARY KEY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  IMAGE_URL VARCHAR(255) NOT NULL,
  ICON VARCHAR(255) NOT NULL,
  INFO TEXT NOT NULL,
  EDIBLE BOOLEAN NOT NULL
);

CREATE TABLE BLOG (
  ID SERIAL PRIMARY KEY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  content TEXT,
  publication_date DATE,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  USER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
  privacy BOOLEAN NOT NULL
);

CREATE TABLE FRIENDS (
  ID SERIAL PRIMARY KEY NOT NULL,
  USER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
  FRIEND_USER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE
);

CREATE TABLE FAVOURITES (
  ID SERIAL PRIMARY KEY NOT NULL,
  USER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
  BLOG_ID INTEGER REFERENCES BLOG(id) ON DELETE CASCADE
);

CREATE TABLE MUSHROOM_POST (
  ID SERIAL PRIMARY KEY NOT NULL,
  BLOG_ID INTEGER REFERENCES BLOG(id) ON DELETE CASCADE,
  MUSHROOM_ID INTEGER REFERENCES MUSHROOM(id) ON DELETE CASCADE
);

CREATE TABLE COMMENTS (
  ID SERIAL PRIMARY KEY NOT NULL,
  BLOG_ID INTEGER REFERENCES BLOG(id) ON DELETE CASCADE,
  COMMENTER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
  message VARCHAR(255) NOT NULL
);