DROP TABLE IF EXISTS USER_ACCOUNT CASCADE;
DROP TABLE IF EXISTS MUSHROOM CASCADE;
DROP TABLE IF EXISTS BLOG CASCADE;

CREATE TABLE USER_ACCOUNT (
  ID SERIAL PRIMARY KEY NOT NULL,
  FULLNAME VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL
);

CREATE TABLE MUSHROOM (
  ID SERIAL PRIMARY KEY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  IMAGE_URL VARCHAR(255) NOT NULL,
  INFO VARCHAR(255) NOT NULL,
  EDIBLE BOOLEAN NOT NULL
);

CREATE TABLE BLOG (
  ID SERIAL PRIMARY KEY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  content TEXT,
  publication_date DATE,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  USER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
  MUSHROOM_ID INTEGER REFERENCES MUSHROOM(id) ON DELETE CASCADE
);