INSERT INTO USER_ACCOUNT (FULLNAME, EMAIL, PASSWORD, PHOTO_URL)
VALUES 
  ('John Doe', 'jdoe@test.com', 'asd', 'https://avatar.iran.liara.run/public/30'),
  ('Alice Wonderland', 'awond@test.com', 'asd', 'https://avatar.iran.liara.run/public/58'),
  ('Sita Dennis', 'sitad@test.com', 'asd', 'https://avatar.iran.liara.run/public/100'),
  ('Sasha Mateo', 'matte@test.com', 'asd', 'https://avatar.iran.liara.run/public/67'),
  ('Anita Austi', 'anita@test.com', 'asd', 'https://avatar.iran.liara.run/public/98'),
  ('Lukas Souza', 'lsouza@test.com', 'asd', 'https://avatar.iran.liara.run/public/5'),
  ('Jose Alejandro', 'josea@test.com', 'asd', 'https://avatar.iran.liara.run/public/49'),
  ('Dwayne Jacob', 'jdwayne@test.com', 'asd', 'https://avatar.iran.liara.run/public/20'),
  ('Allison Saeng', 'saeng@test.com', 'asd', 'https://avatar.iran.liara.run/public/64'),
  ('Adrea Santos', 'santa@test.com', 'asd', 'https://avatar.iran.liara.run/public/86');

INSERT INTO MUSHROOM (TITLE, IMAGE_URL, ICON, INFO, EDIBLE) VALUES
  ('Shaggy Mane', 'mushrooms/shaggy_mane.png', 'mushrooms/shaggy-mane-icon.png', 'The Shaggy Mane mushroom (Coprinus comatus) is recognized by its tall, shaggy, white to cream-colored cap. When young, it has an egg-shaped appearance, and as it matures, the cap opens up, revealing a bell-shaped structure. This mushroom is edible when fresh, but it decomposes rapidly, making timely harvest crucial for culinary use.', true),
  ('Oyster Mushroom', 'mushrooms/oyster_mushroom.png', 'mushrooms/oyster-mushroom-icon.png', 'The Oyster Mushroom (Pleurotus ostreatus) is a popular edible fungus with an oyster-shaped cap and overlapping gills. It comes in various colors and has a mild, anise-like flavor. Often cultivated, these mushrooms grow on decaying wood and are known for their versatility in the kitchen.', true),
  ('King Bolete', 'mushrooms/king_bolete.png', 'mushrooms/king-bolete-icon.png', 'The King Bolete, scientifically known as Boletus edulis, is a highly sought-after and esteemed edible mushroom. Recognizable by its large, convex to flat cap, the King Bolete can reach sizes of up to 12 inches (30 cm) in diameter. The cap is typically brown and covered with a network of fine, net-like ridges. The stem is stout, often swollen towards the base, and can feature a distinctive reticulated pattern (net-like markings).', true),
  ('Saffron Milk Cap', 'mushrooms/saffron_milk_cap.png', 'mushrooms/saffron-milk-cap-icon.png', 'The Saffron Milk Cap, scientifically known as Lactarius deliciosus, is a vibrant and distinctive mushroom widely recognized for its bright orange to reddish cap. The cap is convex in shape, often with a depressed center, and exudes a milky, saffron-colored latex when cut or injured. This latex can stain clothing and hands but is not harmful.', true),
  ('Gem-Studded Puffball', 'mushrooms/gem_studded_puffball.png', 'mushrooms/gem-studded-puffball-icon.png', 'The Gem-Studded Puffball, scientifically known as Lycoperdon perlatum, is a small to medium-sized mushroom characterized by its round shape and distinctive appearance. When young, it features a smooth, white to cream-colored outer skin. As it matures, the surface develops small, pointed, and conical spines or "gems," giving it a spiky or studded appearance. The gems often detach to release spores when the puffball reaches maturity.', true),
  ('Rosy Gomphidius', 'mushrooms/rosy_gomphidius.png', 'mushrooms/rosy-gomphidius-icon.png', 'The Rosy Gomphidius, or Gomphidius subroseus, is a mushroom featuring a bell-shaped cap with a rosy to reddish-brown color and a scaly surface. Adnate gills, close and ranging from white to pinkish, characterize the underside. The slender stem, often with a pinkish hue, may be covered in a whitish substance. Found in association with coniferous trees.', true),
  ('Winter Chanterelle', 'mushrooms/winter_chanterelle.png', 'mushrooms/winter-chanterelle-icon.png', 'The Winter Chanterelle (Craterellus tubaeformis) is a mushroom recognized for its distinctive trumpet-shaped cap, which is yellow to yellow-brown. Lacking true gills, its undersurface exhibits blunt ridges or wrinkles. The stem is hollow and attached to the cap''s underside. Typically found in coniferous or mixed forests, the Winter Chanterelle is notable for fruiting late into fall and winter. Edible and prized for its delicate flavor, it is a sought-after wild mushroom for culinary use.', true),
  ('Pacific Golden Chanterelle', 'mushrooms/pacific_golden_chanterelle.png', 'mushrooms/gold-chanterelle-icon.png', 'The Pacific Golden Chanterelle (Cantharellus formosus) is a widely appreciated wild mushroom known for its vibrant golden-yellow color and distinctive trumpet-shaped cap. The cap is often vase-shaped, with wavy edges and a smooth surface. The gills are usually blunt and run down the stem, which is solid and can also be yellow or paler in color. Found in coniferous and mixed forests along the west coast of North America, particularly in the Pacific Northwest, these chanterelles are mycorrhizal, forming symbiotic relationships with tree roots.', true),
  ('Orange Peel Fungus', 'mushrooms/orange_peel_fungus.png', 'mushrooms/orange-peel-fungus-icon.png', 'The Orange Peel Fungus (Aleuria aurantia) is a distinctive and brightly colored fungus known for its vibrant orange appearance, resembling a crumpled or peeling piece of citrus fruit peel. The fruiting body is cup-shaped, with the outer surface resembling the texture of an orange peel, and it measures a few centimeters in diameter. The interior of the cup may vary in color from pale orange to white. Typically found on the ground in woodlands, heathlands, or disturbed areas, the Orange Peel Fungus is a saprophytic fungus, playing a role in the decomposition of organic matter.', true),
  ('Apricot Jelly', 'mushrooms/apricot_jelly.png', 'mushrooms/apricot-jelly-icon.png', 'The Apricot Jelly is typically cup-shaped, lobed, or irregularly folded, resembling a translucent and gelatinous mass. The color ranges from orange to apricot, giving it the appearance of apricot jelly. The surface can be smooth or slightly wrinkled. This fungus is often found on decaying wood, particularly on coniferous logs, and is more prevalent in cool and moist environments.', true),
  ('Crab Brittlegill', 'mushrooms/crab_brittlegill.png', 'mushrooms/crab-brittlegill-icon.png', 'Russula xerampelina, commonly known as the Shrimp Russula or the Crab Brittlegill, is a mushroom species within the Russulaceae family. It is recognized for its striking cap color, which ranges from pale pinkish-orange to reddish-brown, resembling the color of shrimp or cooked crab. The cap is convex, later flattening, and can grow up to several inches in diameter. The gills are white to pale cream and are spaced closely together. The stem is usually white, firm, and may have a slight reddish tint.', true),
  ('Lobster Mushroom', 'mushrooms/lobster_mushroom.png', 'mushrooms/lobster-mushroom-icon.png', 'The Lobster Mushroom is easily recognized by its bright orange to reddish exterior, resembling the shell of a cooked lobster. It is actually a parasitic fungus that colonizes the host mushroom, transforming its appearance and texture. The original mushroom''s features, such as gills, are often obscured by the Lobster Mushroom''s dense and firm texture. Found in various forest environments, it has a firm and meaty texture when mature. While generally considered safe to eat and appreciated for its unique flavor, it''s important to accurately identify the host mushroom and ensure the Lobster Mushroom is parasite-free before consumption.', true),
  ('Inky Cap', 'mushrooms/inky_cap.png', 'mushrooms/inky-cap-icon.png', 'The Inky Cap typically has a cylindrical or bell-shaped cap that is initially white and then changes to gray and eventually black as it matures. The gills are closely spaced, and the stem is relatively tall and slender. One distinctive feature is the rapid autodigestion of the cap, starting from the edges, which eventually dissolves the entire cap into an inky black liquid. This process gives the mushroom its common name. Inky Caps are often found in disturbed ground, lawns, or wood chip areas. While some species in the Inky Cap group are edible, Coprinus atramentarius should be avoided if consumed with alcohol due to potential adverse reactions.', true),
  ('Toothed Jelly Fungus', 'mushrooms/toothed_jelly_fungus.png', 'mushrooms/toothed-jelly-fungus-icon.png', 'The Toothed Jelly Fungus typically has a gelatinous, translucent, or semi-translucent fruiting body. The surface may be smooth or have a slightly wrinkled appearance. Instead of traditional gills, it features tooth-like structures or spines on the underside, giving it a distinctive appearance. These spines release spores when touched or disturbed. The color can range from white to various shades of brown. Toothed Jelly Fungi are often found on decaying wood, particularly in forested areas.', true),
  ('Horse Mushroom', 'mushrooms/horse_mushroom.png', 'mushrooms/horse-mushroom-icon.png', 'The Horse Mushroom typically has a large, convex to flat cap with a diameter ranging from 5 to 15 centimeters (2 to 6 inches). The cap color is usually white or cream, sometimes with a slightly yellowish tint, and it may develop brownish scales as it matures. The cap surface is smooth, and the edges often curve upward. The gills are crowded, free from the stem, and start off white, turning pink, and eventually dark brown as the mushroom matures. The stem is sturdy, often with a bulbous base, and may have a delicate ring near the top. Horse Mushrooms are found in grassy areas, meadows, and sometimes lawns.', true),
  ('Meadow Mushroom', 'mushrooms/meadow_mushroom.png', 'mushrooms/meadow-mushroom-icon.png', 'The Meadow Mushroom (Agaricus campestris) is a widespread and well-known mushroom species often found in grassy areas and meadows. The cap of the Meadow Mushroom is initially convex, becoming more flat with age, and typically ranges from 3 to 10 centimeters (1 to 4 inches) in diameter. It is smooth and white, sometimes developing a slight tan hue in the center. The cap edges often exhibit remnants of the veil, which may appear as a ring or ring-like zone.', true),
  ('Cauliflower Mushroom', 'mushrooms/cauliflower_mushroom.png', 'mushrooms/cauliflower-mushroom-icon.png', 'The Cauliflower Mushroom (Sparassis crispa) is a unique and distinctive fungus with a large, intricate, and cauliflower-like fruiting body. The mass of tightly packed, convoluted branches gives it the appearance of a pale, cream-colored cauliflower. Unlike traditional mushrooms, the Cauliflower Mushroom doesn''t have a cap, stem, or gills. Instead, it forms a complex, irregularly shaped structure that can reach considerable sizes. Found on the ground in coniferous or hardwood forests, especially in the late summer to autumn.', true),
  ('Hedgehog Mushroom', 'mushrooms/hedgehog_mushroom.png', 'mushrooms/hedgehog-mushroom-icon.png', 'The Hedgehog Mushroom (Hydnum repandum) is a distinctive and edible fungus characterized by its cap with tooth-like spines underneath instead of traditional gills. The cap is typically orange to yellow-brown, and it ranges from convex to flattened with age. The spines, which are soft and tooth-like, are creamy to yellow in color. The stem is typically short and thick, and it shares a similar coloration with the cap. Found in various forest habitats, especially in association with hardwood trees.', true),
  ('Chicken of the Woods', 'mushrooms/chicken_of_the_woods.png', 'mushrooms/chicken-of-the-woods-icon.png', 'The Chicken of the Woods (Laetiporus spp.) is a conspicuous and striking wild mushroom known for its vibrant colors and distinctive shelf-like growth. Depending on the specific species, the cap can range from bright orange to yellow, and the edges may display a wavy or lobed appearance. The undersurface of the cap consists of soft, overlapping shelves with tiny pores rather than gills. The mushroom often grows in large, conspicuous clusters on the bark of trees, resembling the shape of a roosting chicken, hence its name.', true),
  ('Bear''s Head', 'mushrooms/bears_head.png', 'mushrooms/bear''s-head-icon.png', 'The Bear''s Head (Hericium americanum), is a distinctive and edible mushroom recognized for its unique appearance. Instead of a traditional cap and stem, this mushroom forms cascading, icicle-like spines that hang from a central, tough base. The spines are white and can develop a cream or light yellow hue as the mushroom matures. This fungus tends to grow on hardwood trees, particularly oaks. The Bear''s Head is renowned for its delicate, seafood-like flavor.', true),
  ('Lion''s Mane', 'mushrooms/lions_mane.png', 'mushrooms/lion''s-mane-icon.png', 'The Lion''s Mane mushroom (Hericium erinaceus) is a distinctive and edible fungus renowned for its unique appearance. Instead of a traditional cap and stem, this mushroom forms cascading, hair-like spines that give it the appearance of a fluffy mane or a mass of icicles. The color can range from white to cream. Lion''s Mane is typically found on hardwood trees, particularly oaks and beeches. As it matures, the spines may become more pronounced, and the overall size can vary.', true),
  ('Western Giant Puffball', 'mushrooms/western_giant_puffball.png', 'mushrooms/puffball-icon.png', 'The Western Giant Puffball (Calvatia booniana) is a notable mushroom recognized for its large size and distinctive appearance. This fungus typically grows on the ground, and its fruiting body can reach diameters of up to a foot or more. When young, the Western Giant Puffball is roughly spherical, with a smooth, white to cream-colored outer surface. As it matures, the outer skin becomes thicker, and the interior transforms into a mass of powdery spores.', true),
  -- Non-edible:
  ('Death Cap', 'mushrooms/death_cap.png', 'mushrooms/poison-icon.png', 'The Death Cap mushroom (Amanita phalloides) is one of the most toxic and potentially deadly mushrooms known. Its appearance is deceptive, as it often resembles edible mushrooms. The cap is typically greenish to yellowish, sometimes white, with a smooth surface and a distinctive skirt-like ring on the stem. The gills are white, and the stem is usually white, bulbous at the base, and often buried in the ground. The Death Cap contains deadly toxins that can lead to severe liver and kidney damage, and it is responsible for the majority of mushroom-related poisoning fatalities worldwide.', false),
  ('Pholiotina rugosa', 'mushrooms/pholiotina_rugosa.png', 'mushrooms/poison-icon.png', 'Pholiotina rugosa, also known as the Wrinkled Shield or Wrinkled Pholiota, is a small mushroom with distinctive features. The cap is convex and typically brown with a slightly wrinkled or grooved surface, which gives it its characteristic appearance. As the cap expands, it may flatten out and develop a central depression. The gills are crowded, attached to the stem, and are initially white but may become yellowish as the mushroom matures. The stem is slender, often with a ring, and it may have a bulbous base.', false),
  ('Smith''s Amanita', 'mushrooms/smiths_amanita.png', 'mushrooms/poison-icon.png', 'Amanita smithiana, commonly known as Smith''s Amanita or the Smith''s Lepidella. The cap of Amanita smithiana is typically brown, often with shades of yellow or orange. The cap can range from convex to flattened, and it may have remnants of a white to pale yellow veil, especially around the edges. The stem is generally white, slender, and may have a bulbous base. A characteristic feature of this species is the persistent, skirt-like ring on the upper part of the stem.', false),
  ('Deadly Galerina', 'mushrooms/deadly_galerina.png', 'mushrooms/poison-icon.png', 'The Deadly Galerina (Galerina marginata) is a small, toxic mushroom found on decaying wood in coniferous forests. Its cap is typically brown to yellow-brown and convex, with gills attached to the stem that have a brown color. The slender stem may show slight swelling at the base. Recognized by its rusty brown spore print, this mushroom contains lethal amatoxins, which can cause severe liver and kidney damage if ingested.', false),
  ('Deadly Parasol', 'mushrooms/deadly_parasol.png', 'mushrooms/poison-icon.png', 'The Deadly Parasol (Chlorophyllum molybdites) is a poisonous mushroom characterized by a large tan to olive-brown cap with scales, free white gills, a tall stem often swelling at the base, and a loose, skirt-like ring. Distinguished by its greenish spore print, it bears a resemblance to edible parasol mushrooms. Ingesting this species can lead to severe gastrointestinal distress, emphasizing the importance of avoiding consumption.', false),
  ('Fly Agaric', 'mushrooms/fly_agaric.png', 'mushrooms/poison-icon.png', 'The Fly Agaric (Amanita muscaria) is a striking and iconic mushroom known for its distinctive appearance. The cap is typically bright red with white spots, resembling the classic toadstool in fairy tales. The cap can range from 5 to 20 centimeters in diameter and is often convex when young, becoming flatter as it matures. The white gills are free from attachment to the stem and are densely packed. The stem is white, sometimes with a bulbous base, and may have a distinctive ring or skirt-like structure. While visually striking, the Fly Agaric is toxic and contains psychoactive compounds. ', false);

-- 10 Inserts for BLOG table
INSERT INTO BLOG (TITLE, content, publication_date, latitude, longitude, USER_ID, privacy) VALUES
  ('Exploring Chanterelles', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-01-15', 50.15839605653889, -126.6635744422674, 3, true),
  ('The Mystery of the Death Cap', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-02-02', 49.960909365760074, -115.8530275672674, 5, true),
  ('Truffle Hunting Adventure', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-02-20', 50.99557859676613, -121.3461916297674, 1, true),
  ('Magical Amanita Muscaria', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-03-10', 52.08876065107938, -126.2680666297674, 2, true),
  ('Culinary Delight with Shiitake', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-03-25', 53.12944258841553, -121.3022463172674, 7, true),
  ('Morel Mushroom Foraging', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..', '2022-04-05', 53.182145421239646, -128.02099631726742, 4, true),
  ('A Fungus Among Us: Oyster Mushroom', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-04-20', 53.60144255177566, -132.15185569226742, 6, true),
  ('Lions Mane Beauty', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-05-10', 57.446040559523546, -120.98632945503736, 9, true),
  ('Porcini Adventure', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-05-25', 59.154442775922355, -122.26074351753736, 8, true),
  ('Mushroom Spotting with the Truffle Hounds', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-06-05', 58.009172065877394, -129.995118517537386, 1, true);

-- 10 Inserts for FRIENDS table
INSERT INTO FRIENDS (USER_ID, FRIEND_USER_ID, FRIENDSHIP_STATUS) VALUES
  (1, 2, true),
  (1, 3, true),
  (2, 4, true),
  (3, 5, false),
  (4, 6, true),
  (5, 7, false),
  (6, 8, true),
  (7, 9, true),
  (8, 10, false),
  (9, 1, true);

-- 10 Inserts for FAVOURITES table
INSERT INTO FAVOURITES (USER_ID, BLOG_ID) VALUES
  (1, 1),
  (2, 3),
  (3, 5),
  (4, 7),
  (5, 9),
  (6, 2),
  (7, 4),
  (8, 6),
  (9, 8),
  (10, 9),
  (1, 8),
  (1, 9),
  (1, 4);

-- 10 Inserts for MUSHROOM_POST table
INSERT INTO MUSHROOM_POST (BLOG_ID, MUSHROOM_ID) VALUES
  (1, 1),
  (2, 6),
  (3, 10),
  (4, 8),
  (5, 4),
  (6, 2),
  (7, 5),
  (8, 9),
  (9, 7),
  (10, 3),
  (1, 2),
  (1, 3),
  (1, 4),
  (1, 5);

-- 10 Inserts for COMMENTS table
INSERT INTO COMMENTS (BLOG_ID, COMMENTER_ID, MESSAGE) VALUES
  (1, 2, 'Great find! Chanterelles are delicious.'),
  (1, 1, 'Woo-hoo! Chanterelles RULE!.'),
  (1, 5, 'The (Lorem ipsum dolor sit amet) part really makes a good point!'),
  (1, 1, 'MUSHROOMS!'),
  (2, 3, 'Thanks for the warning about the Death Cap. Stay safe!'),
  (3, 4, 'Truffle hunting sounds like an amazing adventure!'),
  (4, 5, 'The Amanita Muscaria is indeed beautiful but dangerous.'),
  (5, 6, 'Shiitake mushrooms are my favorite too!'),
  (6, 7, 'Morel mushrooms have such a unique appearance.'),
  (7, 8, 'Oyster mushrooms are so versatile in cooking.'),
  (8, 9, 'Lions Mane mushrooms are truly fascinating.'),
  (9, 10, 'Porcini risotto must have been delicious!'),
  (10, 1, 'Truffle hounds are incredible at finding treasures.');